channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - c-compiler
  - cxx-compiler
  - hdf5=*=*mpi_mpich*
  - mpi4py
  - pyyaml
  - pip
  - tqdm
  - pytest
  - pytest-mpi
  - pip:
    - pyyaml-include
    - h5py --no-binary=h5py
